Use CIFRA_MX_2011_C


-- Dense Rank (For Walmart) - Final
select 
VND_NBR,
BILL_NBR, 
PO_TOT,
BILL_SUB = DENSE_RANK() OVER ( PARTITION by BILL_NBR ORDER BY VND_NBR, BILL_NBR, PO_TOT),
PO_NBR, POWHSE, POTYPE, PODEPT, VEND_SUB, STAPLE, LBLDATE, PO_Order_Date, PO_FileYr, PO_Unqkey, POUNQCNT
FROM dbo.ARDY_TABLE
Where VND_NBR IN (75, 724)
order by VND_NBR, BILL_NBR, PO_TOT, BILL_SUB


-- Different sample
select 
VND_NBR,
BILL_NBR, 
PO_TOT,
BILL_SUB = ROW_NUMBER() OVER (PARTITION by PO_TOT ORDER BY VND_NBR, BILL_NBR, PO_TOT),
PO_NBR, POWHSE, POTYPE, PODEPT, VEND_SUB, STAPLE, LBLDATE, PO_Order_Date, PO_FileYr, PO_Unqkey, POUNQCNT
FROM dbo.ARDY_TABLE
Where VND_NBR IN (75, 724)
order by VND_NBR, BILL_NBR, PO_TOT, BILL_SUB
